version: "3.4"

volumes:
  HouseBookDB:

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: HouseBook123
    ports:
      - 27017:27017
    volumes:
      - HouseBookDB:/data/db

  housebook:
    image: nicoloso100/housebook:latest
    depends_on:
      - mongo
    ports:
      - "80:4000"
    links:
      - mongo
    environment:
      - MONGODB=mongodb://root:HouseBook123@mongo:27017/HouseBook?authSource=admin
