version: "3.4"

volumes:
  HouseBookVolume:
    name: HouseBookVolume

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: HouseBook123
    ports:
      - 27017:27017
    volumes:
      - HouseBookVolume:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: HouseBook123
    depends_on:
      - mongo
