version: "3.4"

volumes:
  HouseBookVolume:
    name: HouseBookVolume

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: HouseBook123
    ports:
      - 27017:27017
    volumes:
      - HouseBookVolume:/data/db

  housebook:
    image: nicoloso100/housebook:latest
    depends_on:
      - mongo
    ports:
      - "80:4000"
